---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Additional apache security config
  copy:
    src=harden.conf dest={{ apache_confdir }}/security2.conf mode=0644
  notify:
    - restart apache
- name: Debian | symlink active security config for apache
  file: src={{ apache_confdir }}/security2.conf dest=/etc/apache2/conf-enabled/security2.conf state=link
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify:
    - restart apache
- name: ossec-wui apache config
  copy:
    src=apache-ossecwui.conf dest={{ apache_confdir }}/apache-ossecwui.conf mode=0644
  notify:
    - restart apache
- name: Debian | symlink active ossecwui config for apache
  file: src={{ apache_confdir }}/apache-ossecwui.conf dest=/etc/apache2/conf-enabled/ossecwui.conf state=link
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify:
    - restart apache

- name: git clone ossec-wui
  git:
    repo: https://github.com/ossec/ossec-wui.git
    dest: /var/www/html/ossec-wui
    version: HEAD
- name: Creating htpasswd file
  htpasswd:
    path: /var/www/html/ossec-wui/.htpasswd
    name: "{{ ossecwui_webuser }}"
    password: "{{ ossecwui_webpass }}"
    owner: root
    group: "{{ www_user }}"
    mode: '0640'

- name: ensure ossec group exists (normally provided by ossec-server)
  group: name=ossec state=present
- name: ensure {{ www_user }} user in ossec group
  user: name={{ www_user }} groups=ossec append=yes
- name: Ensure /var/ossec/tmp exists
  file: path=/var/ossec/tmp owner=root group={{ www_user }} mode=0770 state=directory

- include: local-etc-hosts-kitchen-lxd.yml

- name: Ensure httpd is enabled and started
  service: name={{ apache_svc }} state=started enabled=yes
